/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conta.bancaria;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author LABORATORIO
 */
public class ContaBancaria extends javax.swing.JFrame {

    /**
     * Creates new form ContaBancaria
     */
    public ContaBancaria() {
        initComponents();
        pnl_Criar.setVisible(false);
        pnl_Acessar.setVisible(false);
        lbl_NomeCliente.setVisible(false);
        lbl_Saldo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_Criar = new javax.swing.JButton();
        pnl_Criar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_Criar_Nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Criar_CPF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spn_Criar_Deposito = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        cbb_TipoConta = new javax.swing.JComboBox<>();
        btn_FinalizarConta = new javax.swing.JButton();
        btn_Sair_Criar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_Acessar = new javax.swing.JButton();
        pnl_Acessar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_CPF_Acesso = new javax.swing.JTextField();
        btn_EntraConta = new javax.swing.JButton();
        lbl_NomeCliente = new javax.swing.JPanel();
        btn_Saque_Acesso = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        spn_Saque_Acesso = new javax.swing.JSpinner();
        btn_Sair_Acesso = new javax.swing.JButton();
        btn_Mensalidade = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbb_TipoConta_Acesso = new javax.swing.JComboBox<>();
        btn_Saldo = new javax.swing.JButton();
        lbl_Saldo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spn_Deposito_Acesso = new javax.swing.JSpinner();
        btn_Deposito_Acesso = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Conta Bancaria - Valverde S.A.");

        btn_Criar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_Criar.setText("Cria Conta");
        btn_Criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CriarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText(" Criar ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        txt_Criar_Nome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Criar_Nome.setText("Jose");
        txt_Criar_Nome.setToolTipText("");
        txt_Criar_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Criar_NomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Digite seu nome completo:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Digite seu CPF:");

        txt_Criar_CPF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Criar_CPF.setText("125688468");
        txt_Criar_CPF.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Primeiro depósito:");

        spn_Criar_Deposito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        spn_Criar_Deposito.setModel(new javax.swing.SpinnerNumberModel(50, 50, null, 5));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Tipo de conta:");

        cbb_TipoConta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbb_TipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Corrente", "Conta Poupança" }));
        cbb_TipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_TipoContaActionPerformed(evt);
            }
        });

        btn_FinalizarConta.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_FinalizarConta.setText("   Finalizar   ");
        btn_FinalizarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FinalizarContaActionPerformed(evt);
            }
        });

        btn_Sair_Criar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Sair_Criar.setText("Sair");
        btn_Sair_Criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sair_CriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_CriarLayout = new javax.swing.GroupLayout(pnl_Criar);
        pnl_Criar.setLayout(pnl_CriarLayout);
        pnl_CriarLayout.setHorizontalGroup(
            pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CriarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_CriarLayout.createSequentialGroup()
                        .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(pnl_CriarLayout.createSequentialGroup()
                                .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(12, 12, 12)
                                .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbb_TipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Criar_Nome))))
                        .addContainerGap())
                    .addGroup(pnl_CriarLayout.createSequentialGroup()
                        .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(70, 70, 70)
                        .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Criar_CPF)
                            .addGroup(pnl_CriarLayout.createSequentialGroup()
                                .addComponent(spn_Criar_Deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_CriarLayout.createSequentialGroup()
                        .addComponent(btn_Sair_Criar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_FinalizarConta)
                        .addGap(138, 138, 138))))
        );
        pnl_CriarLayout.setVerticalGroup(
            pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CriarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbb_TipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Criar_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Criar_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spn_Criar_Deposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_CriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_FinalizarConta)
                    .addComponent(btn_Sair_Criar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Criar)
                    .addComponent(pnl_Criar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_Criar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Criar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Acessar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btn_Acessar.setText("Acessar Conta");
        btn_Acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AcessarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText(" Acessar ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Digite seu CPF:");

        txt_CPF_Acesso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btn_EntraConta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_EntraConta.setText("Entrar");
        btn_EntraConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntraContaActionPerformed(evt);
            }
        });

        btn_Saque_Acesso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Saque_Acesso.setText("Sacar");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Saque:");

        spn_Saque_Acesso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        spn_Saque_Acesso.setModel(new javax.swing.SpinnerNumberModel(50, 50, null, 5));

        btn_Sair_Acesso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Sair_Acesso.setText("Sair");
        btn_Sair_Acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sair_AcessoActionPerformed(evt);
            }
        });

        btn_Mensalidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_Mensalidade.setText("Mensalidade");
        btn_Mensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MensalidadeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Tipo de conta:");

        cbb_TipoConta_Acesso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbb_TipoConta_Acesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Corrente", "Conta Poupança" }));
        cbb_TipoConta_Acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_TipoConta_AcessoActionPerformed(evt);
            }
        });

        btn_Saldo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Saldo.setText("Saldo");

        lbl_Saldo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_Saldo.setText(" R$ 0,00 ");
        lbl_Saldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Depósito: ");

        spn_Deposito_Acesso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        spn_Deposito_Acesso.setModel(new javax.swing.SpinnerNumberModel(50, 50, null, 5));

        btn_Deposito_Acesso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Deposito_Acesso.setText("Depositar");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Cliente");

        javax.swing.GroupLayout lbl_NomeClienteLayout = new javax.swing.GroupLayout(lbl_NomeCliente);
        lbl_NomeCliente.setLayout(lbl_NomeClienteLayout);
        lbl_NomeClienteLayout.setHorizontalGroup(
            lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_NomeClienteLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(cbb_TipoConta_Acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Saldo)
                .addGap(18, 18, 18)
                .addComponent(lbl_Saldo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(lbl_NomeClienteLayout.createSequentialGroup()
                .addGroup(lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbl_NomeClienteLayout.createSequentialGroup()
                        .addGroup(lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spn_Saque_Acesso)
                            .addComponent(spn_Deposito_Acesso))
                        .addGap(18, 18, 18)
                        .addGroup(lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Deposito_Acesso)
                            .addComponent(btn_Saque_Acesso))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(lbl_NomeClienteLayout.createSequentialGroup()
                        .addComponent(btn_Sair_Acesso)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Mensalidade)))
                .addContainerGap())
        );
        lbl_NomeClienteLayout.setVerticalGroup(
            lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_NomeClienteLayout.createSequentialGroup()
                .addGroup(lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Saldo)
                    .addComponent(lbl_Saldo)
                    .addComponent(jLabel12)
                    .addComponent(cbb_TipoConta_Acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spn_Deposito_Acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Deposito_Acesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spn_Saque_Acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Saque_Acesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lbl_NomeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sair_Acesso)
                    .addComponent(btn_Mensalidade)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_AcessarLayout = new javax.swing.GroupLayout(pnl_Acessar);
        pnl_Acessar.setLayout(pnl_AcessarLayout);
        pnl_AcessarLayout.setHorizontalGroup(
            pnl_AcessarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AcessarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_AcessarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_AcessarLayout.createSequentialGroup()
                        .addGroup(pnl_AcessarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_AcessarLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txt_CPF_Acesso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_EntraConta))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_AcessarLayout.setVerticalGroup(
            pnl_AcessarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AcessarLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pnl_AcessarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_CPF_Acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_EntraConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Acessar)
                    .addComponent(pnl_Acessar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Acessar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Acessar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AcessarActionPerformed
        pnl_Acessar.setVisible(true);
        pnl_Criar.setVisible(false);
    }//GEN-LAST:event_btn_AcessarActionPerformed

    private void btn_CriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CriarActionPerformed
        pnl_Criar.setVisible(true);
        pnl_Acessar.setVisible(false);
    }//GEN-LAST:event_btn_CriarActionPerformed

    private void txt_Criar_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Criar_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Criar_NomeActionPerformed

    private void cbb_TipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_TipoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_TipoContaActionPerformed

    private void btn_EntraContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntraContaActionPerformed

        Contas conta = new Contas();
        //String[] vetor = conta.getCadastroCPF();

        conta.acessoConta();
        System.out.println(conta.getNome() + "  " + conta.getCpf() + "  " + conta.getSaldo() + "   " + conta.getTipoConta());

        /*
        String cpf = txt_CPF_Acesso.getText(); // 132.611.666-57
        if ("".equals(cpf)) {
            JOptionPane.showMessageDialog(null, "Dados Incompletos!", "Erro", WARNING_MESSAGE);
        } else {
            boolean ok = false;
            for (int c = 0; c < vetor.length; c++) {
                //System.out.println("Main: " + vetor[c]);
                if (cpf.equals(vetor[c])) {
                    ok = true;
                    break;
                } else {
                    ok = false;
                }
            }
            if (ok == true) {
                lbl_NomeCliente.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "CPF não cadastrado!", "Erro", WARNING_MESSAGE);
            }
        }
         */

    }//GEN-LAST:event_btn_EntraContaActionPerformed

    private void btn_MensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MensalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MensalidadeActionPerformed

    private void cbb_TipoConta_AcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_TipoConta_AcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_TipoConta_AcessoActionPerformed

    private void btn_Sair_AcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sair_AcessoActionPerformed
        int resposta = (int) JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Cinfirmação", WARNING_MESSAGE);
        if (resposta == 0) { // 0 = confirma, 2 = cancela
            lbl_NomeCliente.setVisible(false);
            pnl_Acessar.setVisible(false);
        }
    }//GEN-LAST:event_btn_Sair_AcessoActionPerformed

    private void btn_Sair_CriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sair_CriarActionPerformed
        int resposta = (int) JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Cinfirmação", WARNING_MESSAGE);
        if (resposta == 0) { // 0 = confirma, 2 = cancela
            pnl_Criar.setVisible(false);
        }
    }//GEN-LAST:event_btn_Sair_CriarActionPerformed

    private void btn_FinalizarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FinalizarContaActionPerformed
        Contas pessoa = new Contas();
        String nome = txt_Criar_Nome.getText();
        String cpf = txt_Criar_CPF.getText();
        int tipo = cbb_TipoConta.getSelectedIndex(); // 0 Corrente, 1 poupança
        int saldo = (int) spn_Criar_Deposito.getValue();
        char tipoConta = 'C';

        if (tipo == 0) {
            tipoConta = 'C';
        } else {
            tipoConta = 'P';
        }

        if ("".equals(nome) || "".equals(cpf)) {
            JOptionPane.showMessageDialog(null, "Dados Incompletos!", "Erro", WARNING_MESSAGE);
        } else {
            pessoa.novaConta(nome, cpf, tipoConta, saldo);
        }
    }//GEN-LAST:event_btn_FinalizarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaBancaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaBancaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaBancaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaBancaria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaBancaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Acessar;
    private javax.swing.JButton btn_Criar;
    private javax.swing.JButton btn_Deposito_Acesso;
    private javax.swing.JButton btn_EntraConta;
    private javax.swing.JButton btn_FinalizarConta;
    private javax.swing.JButton btn_Mensalidade;
    private javax.swing.JButton btn_Sair_Acesso;
    private javax.swing.JButton btn_Sair_Criar;
    private javax.swing.JButton btn_Saldo;
    private javax.swing.JButton btn_Saque_Acesso;
    private javax.swing.JComboBox<String> cbb_TipoConta;
    private javax.swing.JComboBox<String> cbb_TipoConta_Acesso;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lbl_NomeCliente;
    private javax.swing.JLabel lbl_Saldo;
    private javax.swing.JPanel pnl_Acessar;
    private javax.swing.JPanel pnl_Criar;
    private javax.swing.JSpinner spn_Criar_Deposito;
    private javax.swing.JSpinner spn_Deposito_Acesso;
    private javax.swing.JSpinner spn_Saque_Acesso;
    private javax.swing.JTextField txt_CPF_Acesso;
    private javax.swing.JTextField txt_Criar_CPF;
    private javax.swing.JTextField txt_Criar_Nome;
    // End of variables declaration//GEN-END:variables

}
